package middleware

import (
	"net/http"
	"strings"
)

// SecurityHeaders sets the browser hardening headers on every response.
//
// Until now the server set none of these and left them to the reverse proxy,
// which the documentation never asked operators to add. The embedded SPA was
// therefore frameable and MIME-sniffable on a default install. These headers
// are safe to send unconditionally: an operator who wants different values can
// still override them at the proxy, which wins because it writes last.
//
// csp is the Content-Security-Policy value. An empty string sends no CSP
// header at all, for operators who set their own policy at the proxy or need
// to debug a blocked resource. Swagger UI under /api-docs ships inline
// scripts, so the CSP is skipped for that path only; the other headers still
// apply there.
func SecurityHeaders(csp string) func(http.Handler) http.Handler {
	csp = strings.TrimSpace(csp)
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			h := w.Header()
			h.Set("X-Content-Type-Options", "nosniff")
			h.Set("X-Frame-Options", "SAMEORIGIN")
			h.Set("Referrer-Policy", "strict-origin-when-cross-origin")
			h.Set("Permissions-Policy", "camera=(), microphone=(), geolocation=()")
			// The SPA already carries a noindex meta tag; the header covers
			// API responses and files the meta tag cannot reach.
			h.Set("X-Robots-Tag", "noindex, nofollow, noarchive, nosnippet")
			if csp != "" && !isSwaggerPath(r.URL.Path) {
				h.Set("Content-Security-Policy", csp)
			}
			next.ServeHTTP(w, r)
		})
	}
}

// isSwaggerPath matches the Swagger UI mount (/api/v1/api-docs and anything
// under it). Its HTML is generated by http-swagger with inline scripts that a
// 'self'-only script-src would block.
func isSwaggerPath(p string) bool {
	return strings.Contains(p, "/api-docs")
}
